In [27]:
import pandas as pd
import numpy as np
import string

In [28]:
stores_df = pd.read_csv('us_supermarkets.csv')
stores_df.columns = ['nothing', 'store_name', 'lat', 'lon']
stores_df = stores_df.drop(columns=['nothing'])
stores_df.head()

            store_name        lat        lon
0          foot outlet  33.612083 -85.963274
1           Winn Dixie  33.597828 -85.928149
2               Target  33.608768 -85.783059
3               Target  33.224346 -86.804360
4  Walmart Supercenter  33.235489 -86.801210

In [32]:
sort_df = stores_df.sort_values(by='store_name', ascending=True)

sort_df.store_name = sort_df.store_name.apply(lambda x: x.lower())
sort_df.store_name = sort_df.store_name.apply(lambda x: x.translate(string.punctuation))


sort_df.store_name

                                      store_name        lat         lon
10567                     (hispanic) supermarket  39.961956  -75.157610
3508                                           .  30.626478  -81.546757
572                                       10 box  36.335559  -94.142498
1093                          1001 castro street  37.753625 -122.434306
10821                      14 carrot whole foods  34.004570  -81.206200
6673                              168 asian mart  42.530759  -83.108772
730                                   168 market  34.104539 -118.087322
729                                   168 market  34.080386 -118.109955
259                           17th street market  32.212998 -110.958653
12883                 18th street grocery & deli  47.010700 -120.540231
5178                           1st choice market  41.613028  -87.514866
11344                              2nd st market  30.263956  -97.742320
12007                            3 amigos market  37.113740 -113.596063
5863                      4 corners shop 'n save  44.643542  -67.762360
8287                            48th street deli  40.760704  -73.908519
8418                             4th street deli  40.723155  -73.982699
8430                       4th street food co-op  40.726650  -73.990796
8702                                   5 de mayo  40.747452  -73.884560
1703   6001 california market (appel & dietrich)  37.783906 -122.481967
4394                                    7 eleven  21.286382 -157.833177
1971                                    7 eleven  34.052791 -118.313961
3533                                    7 eleven  28.520435  -81.376183
8253                                    7 eleven  40.766846  -73.540566
10522                                   7 eleven  39.998670  -75.108840
2113                                    7 eleven  33.990234 -118.447294
8158                                    7 eleven  40.755447  -73.888045
8524                                    7 eleven  40.843216  -73.836370
1563                                        7-11  33.930566 -118.416226
4740                                        7-11  42.025108  -88.114726
12446                                       7-11  38.952580  -77.225392
1718                                        7-11  37.526116 -121.986203
1634                                    7-eleven  38.232366 -122.637429
3551                                    7-eleven  26.156357  -81.797361
2318                                    7-eleven  32.722091 -117.159171
13341                                   7-eleven  38.908532  -77.032154
10638                                   7-eleven  41.815310  -71.419992
3550                                    7-eleven  26.203323  -81.799710
6405                                    7-eleven  42.350411  -71.077303
12008                                   7-eleven  40.373784 -111.786507
12739                                   7-eleven  47.616052 -122.335895
2086                                    7-eleven  34.055343 -118.441287
7495                                    7-eleven  36.113531 -115.163530
1503                                    7-eleven  38.683552 -121.457418
4759                                    7-eleven  41.892404  -87.622532
2082                                    7-eleven  33.908870 -118.331072
12472                                   7-eleven  38.423824  -77.408605
4978                                    7-eleven  41.890672  -87.627862
1613                                     7eleven  33.901682 -118.106184
2079                                     7eleven  34.062738 -118.445605
8568                          7th avenue gourmet  40.674929  -73.974973